name: Sync Development to Main


on:
  push:
    branches: [development]
  workflow_dispatch:


permissions:
  actions: write
  contents: write
  checks: write
  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: recursive
          ref: development

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install make cmake gcc g++ build-essential pkg-config doxygen

      - name: Build Project
        run: |
          cmake . -DINIP_ENABLE_GOOGLETEST=ON
          make  -j $(nproc)
          make docs
        
      - name: Run Googletests
        run: |
          ctest -V .

      - name: Sync To Main (Merge)
        run: |
          git fetch origin main development
          git checkout -B main origin/main

          if git merge development -m "Auto merge development into main [skip ci]";then
            echo "Merge successful"
          else
            echo "Merge conflict detected"
            git merge --abort
            exit 1
          fi
          git push origin main


